#!/usr/bin/env bash
set -euo pipefail

# shellcheck disable=SC2059
log_normal() {
	if [ $# -gt 0 ]; then
		printf "$@" >&2
	fi
	printf "\n" >&2
}

# shellcheck disable=SC2059
log_underlined() {
	line="$(printf "$@")"
	printf "%s\n" "${line}" >&2
	printf "%s\n" "${line//?/=}" >&2
}

scopes=()
prefix=""
create_png=false
verbose=false

readarray -t available_docs < <(find examples -type f -name "igrmk-*.tex")

for i in "${!available_docs[@]}"; do
	available_docs[i]="$(basename "${available_docs[$i]}" | sed -E 's/^igrmk-([^\.]*)(\.ignore)?\.tex$/\1/')"
done

readarray -t available_docs < <(printf "%s\n" "${available_docs[@]}" | sort)

available_scopes=("all" "${available_docs[@]}")
comma_separated_available_scopes=$(printf ", %s" "${available_scopes[@]}")
comma_separated_available_scopes=${comma_separated_available_scopes:2}

usage() {
	log_normal "Usage: $0 [-h] [-s SCOPE] [-p PREFIX] [-c] [-v]"
	log_normal
	log_normal "Options:"
	log_normal "  -h           Display this help message and exit"
	log_normal "  -s SCOPE     Specify the examples scope. Must be one of:"
	log_normal "               $comma_separated_available_scopes"
	log_normal "               Default: all"
	log_normal "  -p PREFIX    Add a prefix to the output file names"
	log_normal "  -c           Create PNGs in the build output"
	log_normal "  -v           Be verbose"
}

while getopts "hs:p:cv" opt; do
	case "$opt" in
		s)
			scopes+=("$OPTARG")
			;;
		p)
			prefix="$OPTARG"
			;;
		c)
			create_png=true
			;;
		v)
			verbose=true
			;;
		?)
			usage
			exit 1
			;;
	esac
done

if [[ ${#scopes[@]} -eq 0 ]]; then
	log_normal "Building all available examples..."
	scopes=("all")
fi

shift "$((OPTIND - 1))"

if [[ "$#" -ne 0 ]]; then
	log_normal "Only flags are allowed. Extra arguments provided."
	log_normal
	usage
	exit 1
fi

is_valid_scope() {
	for available_scope in "${available_scopes[@]}"; do
		if [[ "$1" = "$available_scope" ]]; then
			return 0
		fi
	done
	return 1
}

for scope in "${scopes[@]}"; do
	if ! is_valid_scope "$scope"; then
		log_normal "Error: scope must be one of: $comma_separated_available_scopes"
		exit 1
	fi
done

for scope in "${scopes[@]}"; do
	if [[ "$scope" = "all" ]]; then
		scopes=("${available_docs[@]}")
		break
	fi
done

build_file() {
	well_known_tectonic_bug_patterns=(
		"warning: 1024-byte read failed"
		"caused by: failed to fill whole buffer"
		"warning: Could not find any valid object\."
	)
	IFS='|' well_known_tectonic_bug_pattern="^(${well_known_tectonic_bug_patterns[*]})$"

	log_underlined "PROCESSING '$1'"
	additinal_options=()
	if [[ $verbose = true ]]; then
		additional_options+=(--print)
	fi
	tectonic "${additional_options[@]}" --color never -Z search-path=. -o output "examples/$1.tex" 2> >(
		# Suppress warnings due to well-known bugs
		grep -v -E "$well_known_tectonic_bug_pattern" >&2
	)

	output_name="$1"
	output_name="${output_name%.ignore}"

	if [[ -n "$prefix" ]]; then
		output_name="$prefix-$1"
	fi

	if [[ "$output_name" != "$1" ]]; then
		mv "output/$1.pdf" "output/$output_name.pdf"
	fi

	log_normal "DONE"
	log_normal

	if [[ $create_png = true ]]; then
		well_known_poppler_bug_patterns=(
			"Syntax Warning: Couldn't link the profiles"
			"Syntax Warning: Can't create Lab transform"
		)
		IFS='|' well_known_poppler_bug_pattern="^(${well_known_poppler_bug_patterns[*]})$"

		log_underlined "CREATING PNG FOR '$1'"
		pdftoppm -singlefile -png -r 300 "output/$output_name.pdf" "output/$output_name" 2> >(
			# Suppress warnings due to poppler bug: https://gitlab.freedesktop.org/poppler/poppler/-/issues/1524
			grep -v -E "$well_known_poppler_bug_pattern" >&2
		)
		log_normal "DONE"
		log_normal
	fi
}

cd "$(dirname "$0")"
mkdir -p output

for scope in "${scopes[@]}"; do
	if [[ -f "examples/igrmk-$scope.tex" ]]; then
		build_file "igrmk-$scope"
	elif [[ -f "examples/igrmk-$scope.ignore.tex" ]]; then
		build_file "igrmk-$scope.ignore"
	fi
done
