#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 1 ]; then
	printf "%s\n" "Usage: $0 <version>"
	exit 1
fi

version=$1

if ! git diff-index --quiet HEAD --; then
	echo "Error: Git working directory is not clean"
	#exit 1
fi

gawk -i inplace -v version="$version" '
	/^\\ProvidesClass{juicv}/ {
		$0 = \
			"\\ProvidesClass{juicv}[" \
			strftime("%Y/%m/%d") \
			" " \
			version \
			" LaTeX CV class focused on compactness]"
	}
	1
' juicv.cls


msg="Release $version"
git add juicv.cls
git commit -m "$msg"
echo "Created commit with message: $msg"
git tag -a "$version" -m "$msg"
echo "Created annotated tag $version with message: $msg"
