#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 1 ]; then
	printf "%s\n" "Usage: $0 <file>"
	exit 1
fi

# shellcheck disable=SC2059
log_normal() {
	if [ $# -gt 0 ]; then
		printf "$@" >&2
	fi
	printf "\n" >&2
}

pdf=$1

mkdir -p logs
log_normal "Running qpdf..."
qpdf --check "$pdf" > logs/qpdf.log || log_normal FAILED
log_normal "Running pdftk..."
pdftk "$pdf" output /dev/null > logs/pdftk.log || log_normal FAILED
log_normal "Running gs..."
gs -o /dev/null -sDEVICE=pdfwrite "$pdf" > logs/gs.log || log_normal FAILED
log_normal "Running verapdf..."
verapdf --format json --success "$pdf" > logs/verapdf.log || log_normal FAILED
log_normal "Running mutool..."
mutool clean -gggg "$pdf" > logs/mutool.log || log_normal FAILED

rm out.pdf
