#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 1 ]; then
	printf "%s\n" "Usage: $0 <file>"
	exit 1
fi

# shellcheck disable=SC2059
log_normal() {
	printf "$@" >&2
}

pdf=$1

mkdir -p logs

commands=(
	"qpdf --check '$pdf' > logs/qpdf.log"
	"pdftk '$pdf' output /dev/null > logs/pdftk.log"
	"gs -o /dev/null -sDEVICE=pdfwrite '$pdf' > logs/gs.log"
	"verapdf --format json --success '$pdf' > logs/verapdf.log"
	"mutool clean -gggg '$pdf' > logs/mutool.log"
	"pdfimages -list '$pdf' 2> logs/pdfimages.log > /dev/null && [[ ! -s logs/pdfimages.log ]]"
)

for cmd in "${commands[@]}"; do
	log_normal "Running ${cmd%% *}..."
	if eval "$cmd"; then
		log_normal " OK\n"
	else
		log_normal " FAILED\n"
	fi
done

rm out.pdf
